2025-03-20 11:26:34.179 +07 | INFO     | Line   10 (task_load_data.py): Starting document loading process into Qdrant...
2025-03-20 11:27:52.220 +07 | INFO     | Line   10 (task_load_data.py): Starting document loading process into Qdrant...
2025-03-20 11:29:11.754 +07 | INFO     | Line   10 (task_load_data.py): Starting document loading process into Qdrant...
2025-03-20 11:29:12.069 +07 | INFO     | Line   27 (qdrant_service.py): Starting document loading process...
2025-03-20 11:29:12.072 +07 | ERROR    | Line   53 (qdrant_service.py): Error loading documents: 'function' object has no attribute 'error'
2025-03-20 11:29:12.072 +07 | ERROR    | Line   21 (task_load_data.py): Failed to load documents: 'function' object has no attribute 'error'
2025-03-20 11:42:36.826 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:42:37.142 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:42:37.143 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:42:38.581 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:42:38.581 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:42:38.581 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:13.892 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:45:14.200 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:45:14.201 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:45:14.643 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:14.643 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:14.643 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:48.351 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:45:48.649 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:45:48.649 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:45:49.869 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:49.869 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:49.869 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:45:55.158 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:45:55.474 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:45:55.474 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:45:55.474 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:45:55.474 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:46:18.538 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:46:18.847 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:46:18.848 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:46:19.668 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:46:19.668 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:46:19.669 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:46:57.344 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:46:57.633 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:46:57.633 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:46:58.302 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:46:58.303 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:46:58.303 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:47:12.157 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:47:12.528 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:47:12.528 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:47:12.529 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:47:12.529 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:48:31.112 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:48:31.421 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:48:31.421 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:48:32.279 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:48:32.279 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:48:32.279 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:49:27.917 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:49:28.227 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:49:28.228 +07 | INFO     | Line  118 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:49:28.907 +07 | ERROR    | Line  103 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:49:28.907 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:49:28.907 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:08.101 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:50:08.406 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:50:08.406 +07 | INFO     | Line  119 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:50:08.406 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:50:08.406 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:50:24.283 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:50:24.585 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:50:24.585 +07 | INFO     | Line  119 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:50:25.432 +07 | ERROR    | Line  104 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:25.432 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:25.432 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:52.035 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:50:52.320 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:50:52.320 +07 | INFO     | Line  119 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:50:52.670 +07 | ERROR    | Line  104 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:52.670 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:50:52.670 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:51:24.377 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:51:24.681 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:51:24.682 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:51:25.542 +07 | ERROR    | Line  102 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:51:25.542 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:51:25.542 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:51:49.335 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:51:49.636 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:51:49.636 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:51:49.636 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:51:49.636 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:52:00.150 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:52:00.451 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:52:00.452 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:52:00.871 +07 | ERROR    | Line  102 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:00.871 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:00.871 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:31.698 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:52:31.991 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:52:31.991 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:52:32.410 +07 | ERROR    | Line  102 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:32.410 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:32.410 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:52:42.014 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:52:42.311 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:52:42.311 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:52:42.312 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:52:42.312 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:53:28.727 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:53:29.085 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:53:29.085 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:53:29.085 +07 | WARNING  | Line   37 (qdrant_service.py): No documents found for processing.
2025-03-20 11:53:29.085 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Unknown error
2025-03-20 11:53:39.060 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:53:39.401 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:53:39.401 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:53:39.790 +07 | ERROR    | Line  102 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:53:39.790 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:53:39.790 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:54:32.527 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:54:32.829 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:54:32.829 +07 | INFO     | Line  117 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:54:33.796 +07 | ERROR    | Line  102 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:54:33.796 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:54:33.797 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:04.893 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:55:05.204 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:55:05.204 +07 | INFO     | Line  119 (embedding.py): No documents provided. Loading from data directory...
2025-03-20 11:55:05.793 +07 | ERROR    | Line  104 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:05.793 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:05.793 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:49.886 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:55:50.193 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:55:50.966 +07 | ERROR    | Line  104 (embedding.py): Error while embedding texts: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:50.966 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:55:50.966 +07 | ERROR    | Line   21 (task_load_data.py): ‚ùå Failed to load documents: Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 11:56:26.127 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:56:26.410 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:56:27.565 +07 | INFO     | Line   40 (qdrant_service.py): Processed 22 document chunks.
2025-03-20 11:56:27.581 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 11:56:27.582 +07 | INFO     | Line   19 (task_load_data.py): ‚úÖ Successfully loaded 22 document chunks into Qdrant.
2025-03-20 11:58:06.718 +07 | INFO     | Line    9 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 11:58:07.075 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 11:58:08.904 +07 | INFO     | Line   40 (qdrant_service.py): Processed 22 document chunks.
2025-03-20 11:58:08.947 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 11:58:08.948 +07 | INFO     | Line   19 (task_load_data.py): ‚úÖ Successfully loaded 22 document chunks into Qdrant.
2025-03-20 12:19:37.411 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:19:37.952 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:19:37.953 +07 | ERROR    | Line  116 (application.py): Error processing investigation: 'DocumentRetriever' object has no attribute 'retrieve'
2025-03-20 12:22:19.423 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:22:19.931 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:22:23.190 +07 | INFO     | Line   89 (application.py): Retrieved 10 documents.
2025-03-20 12:22:33.731 +07 | INFO     | Line   94 (application.py): Top 5 ranked documents selected.
2025-03-20 12:22:33.731 +07 | ERROR    | Line  116 (application.py): Error processing investigation: PerformLLM.generate_report() takes 2 positional arguments but 4 were given
2025-03-20 12:24:51.096 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:24:51.618 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:24:54.024 +07 | INFO     | Line   89 (application.py): Retrieved 10 documents.
2025-03-20 12:25:00.059 +07 | INFO     | Line   94 (application.py): Top 5 ranked documents selected.
2025-03-20 12:25:00.060 +07 | ERROR    | Line  116 (application.py): Error processing investigation: 'confidence'
2025-03-20 12:33:42.760 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:33:43.289 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:33:45.782 +07 | INFO     | Line   89 (application.py): Retrieved 10 documents.
2025-03-20 12:33:51.307 +07 | INFO     | Line   94 (application.py): Top 5 ranked documents selected.
2025-03-20 12:33:51.308 +07 | ERROR    | Line  116 (application.py): Error processing investigation: 'text'
2025-03-20 12:34:07.321 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:34:07.826 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:34:10.974 +07 | INFO     | Line   89 (application.py): Retrieved 10 documents.
2025-03-20 12:34:16.811 +07 | INFO     | Line   94 (application.py): Top 5 ranked documents selected.
2025-03-20 12:34:23.461 +07 | INFO     | Line   98 (application.py): Investigation report generated.
2025-03-20 12:34:23.461 +07 | ERROR    | Line  116 (application.py): Error processing investigation: 'S3Handler' object has no attribute 'save_report'
2025-03-20 12:34:59.648 +07 | INFO     | Line   57 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:35:00.202 +07 | INFO     | Line   77 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:35:03.709 +07 | INFO     | Line   89 (application.py): Retrieved 10 documents.
2025-03-20 12:35:09.336 +07 | INFO     | Line   94 (application.py): Top 5 ranked documents selected.
2025-03-20 12:35:16.505 +07 | INFO     | Line   98 (application.py): Investigation report generated.
2025-03-20 12:40:50.669 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:40:51.083 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:40:53.710 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 12:41:00.056 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 12:41:06.507 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 12:42:51.593 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:42:51.938 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:42:55.465 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 12:43:01.195 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 12:43:08.978 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 12:47:03.585 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:47:04.413 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:47:07.740 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 12:47:07.740 +07 | ERROR    | Line  106 (application.py): Error processing investigation: 'function' object has no attribute 'error'
2025-03-20 12:48:39.869 +07 | INFO     | Line    6 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 12:48:40.159 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 12:48:41.782 +07 | INFO     | Line   40 (qdrant_service.py): Processed 22 document chunks.
2025-03-20 12:48:41.782 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 12:48:41.783 +07 | INFO     | Line   11 (task_load_data.py): ‚úÖ Successfully loaded 22 document chunks into Qdrant.
2025-03-20 12:55:52.655 +07 | INFO     | Line    6 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 12:55:52.951 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 12:55:54.674 +07 | INFO     | Line   40 (qdrant_service.py): Processed 22 document chunks.
2025-03-20 12:55:54.714 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 12:55:54.714 +07 | INFO     | Line   11 (task_load_data.py): ‚úÖ Successfully loaded 22 document chunks into Qdrant.
2025-03-20 12:59:29.053 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 12:59:29.504 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 12:59:32.973 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 12:59:38.994 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 12:59:48.003 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:09:35.806 +07 | INFO     | Line    6 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 13:09:36.109 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 13:09:36.109 +07 | ERROR    | Line   59 (qdrant_service.py): Error loading documents: 'Embedding' object has no attribute '_generate_chunks'
2025-03-20 13:09:36.110 +07 | ERROR    | Line   13 (task_load_data.py): ‚ùå Failed to load documents: 'Embedding' object has no attribute '_generate_chunks'
2025-03-20 13:10:49.069 +07 | INFO     | Line    6 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 13:10:49.365 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 13:10:50.952 +07 | INFO     | Line   40 (qdrant_service.py): Processed 22 document chunks.
2025-03-20 13:10:50.986 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 13:10:50.987 +07 | INFO     | Line   11 (task_load_data.py): ‚úÖ Successfully loaded 22 document chunks into Qdrant.
2025-03-20 13:11:12.941 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 13:11:13.326 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:11:16.350 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:11:22.435 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 13:11:30.680 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:13:04.156 +07 | INFO     | Line    6 (task_load_data.py): üöÄ Starting document loading process into Qdrant...
2025-03-20 13:13:04.439 +07 | INFO     | Line   32 (qdrant_service.py): Starting document loading process...
2025-03-20 13:13:05.812 +07 | INFO     | Line   40 (qdrant_service.py): Processed 8 document chunks.
2025-03-20 13:13:05.828 +07 | INFO     | Line   50 (qdrant_service.py): Successfully uploaded documents to Qdrant.
2025-03-20 13:13:05.829 +07 | INFO     | Line   11 (task_load_data.py): ‚úÖ Successfully loaded 8 document chunks into Qdrant.
2025-03-20 13:13:26.142 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 13:13:26.515 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:13:29.982 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:13:36.121 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 13:13:44.210 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:14:26.247 +07 | INFO     | Line   56 (application.py): Received investigation query: 
2025-03-20 13:14:30.803 +07 | INFO     | Line   75 (application.py): Query is valid: Query: The query provided is empty, meaning it does not contain any information or context that can be evaluated. Without any content, it is imposs...
2025-03-20 13:14:34.387 +07 | ERROR    | Line  106 (application.py): Error processing investigation: Error code: 400 - {'error': {'message': "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2025-03-20 13:14:39.164 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 13:14:39.498 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:14:42.584 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:14:53.127 +07 | INFO     | Line   92 (application.py): Top 5 ranked documents selected.
2025-03-20 13:15:04.288 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:16:13.358 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 13:16:13.708 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:16:17.381 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:16:23.136 +07 | INFO     | Line   92 (application.py): Top 10 ranked documents selected.
2025-03-20 13:16:32.865 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:18:50.406 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack in 2024
2025-03-20 13:18:50.772 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:18:53.467 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:18:59.809 +07 | INFO     | Line   92 (application.py): Top 10 ranked documents selected.
2025-03-20 13:19:10.050 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:20:56.338 +07 | INFO     | Line   56 (application.py): Received investigation query: Find transactions related to the Binance exchange hack
2025-03-20 13:20:56.904 +07 | INFO     | Line   75 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:20:59.458 +07 | INFO     | Line   87 (application.py): Retrieved 10 documents.
2025-03-20 13:21:08.426 +07 | INFO     | Line   92 (application.py): Top 10 ranked documents selected.
2025-03-20 13:21:17.641 +07 | INFO     | Line   96 (application.py): Investigation report generated.
2025-03-20 13:51:35.323 +07 | INFO     | Line   59 (application.py): Received investigation query: Find transactions related to Binance hack from investigator_001
2025-03-20 13:51:35.678 +07 | INFO     | Line   78 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:51:38.994 +07 | INFO     | Line   90 (application.py): Retrieved 10 documents.
2025-03-20 13:51:44.725 +07 | INFO     | Line   95 (application.py): Top 10 ranked documents selected.
2025-03-20 13:51:52.610 +07 | INFO     | Line  100 (application.py): Investigation report generated.
2025-03-20 13:52:35.638 +07 | INFO     | Line   59 (application.py): Received investigation query: Find all cryptocurrency fraud cases from 12345
2025-03-20 13:52:36.014 +07 | INFO     | Line   78 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 13:52:42.691 +07 | INFO     | Line   90 (application.py): Retrieved 10 documents.
2025-03-20 13:52:48.726 +07 | INFO     | Line   95 (application.py): Top 10 ranked documents selected.
2025-03-20 13:52:58.512 +07 | INFO     | Line  100 (application.py): Investigation report generated.
2025-03-20 14:03:08.840 +07 | INFO     | Line   59 (application.py): Received investigation query: Find all cryptocurrency fraud cases from detective_001
2025-03-20 14:03:09.197 +07 | INFO     | Line   78 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 14:03:11.938 +07 | INFO     | Line   90 (application.py): Retrieved 10 documents.
2025-03-20 14:03:17.775 +07 | INFO     | Line   95 (application.py): Top 10 ranked documents selected.
2025-03-20 14:03:27.499 +07 | INFO     | Line  100 (application.py): Investigation report generated.
2025-03-20 14:06:55.778 +07 | INFO     | Line   59 (application.py): Received investigation query: Find all cryptocurrency fraud cases from detective_001
2025-03-20 14:06:56.282 +07 | INFO     | Line   78 (application.py): Query is valid: Query includes relevant investigation-related terms.
2025-03-20 14:07:00.292 +07 | INFO     | Line   90 (application.py): Retrieved 10 documents.
2025-03-20 14:07:06.335 +07 | INFO     | Line   95 (application.py): Top 10 ranked documents selected.
2025-03-20 14:07:18.003 +07 | INFO     | Line  100 (application.py): Investigation report generated.
